---
rbac:
  enabled: true

exporter:
  env:
    FLUENTBIT__LOGGLY_HOST:
    FLUENTBIT__LOGGLY_TOKEN:
    FLUENTBIT__LOGZIO_HOST:
    FLUENTBIT__LOGZIO_TOKEN:
    FLUENTBIT__SLACK_URL:
    FLUENTBIT__DATADOG_HOST:
    FLUENTBIT__DATADOG_API_KEY:
