---
rbac:
  enabled: true

exporter:
  image:
    repository: cr.fluentbit.io/fluent/fluent-bit
    tag: 4.0.7
    pullPolicy: IfNotPresent
  tolerations:
    # Don't deploy onto the K8s master node
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  env:
    FLUENTBIT__LOGGLY_HOST:
    FLUENTBIT__LOGGLY_TOKEN:
    FLUENTBIT__LOGZIO_HOST:
    FLUENTBIT__LOGZIO_TOKEN:
    FLUENTBIT__SLACK_URL:
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      memory: 500Mi
