---
rbac:
  enabled: true

exporter:
  env:
    FLUENTBIT__SLACK_HOST:
    FLUENTBIT__SLACK_TOKEN:
    FLUENTBIT__LOGGLY_HOST:
    FLUENTBIT__LOGGLY_TOKEN:
    FLUENTBIT__DATADOG_HOST:
    FLUENTBIT__DATADOG_API_KEY:
