# To point shell to minikube's docker-daemon:
# `eval $(minikube docker-env)`
# To revert:
# `eval $(minikube docker-env --unset)`

rbac:
  enabled: true

exporter:
  image:
    repository: "noosenergy/fluentd"
    tag: latest
    # To be set @ `Never` otherwise minikube upload from network
    pullPolicy: Never
  tolerations:
    # Don't deploy onto the K8s master node
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  env:
    FLUENTD__LOGGLY_URL:
    FLUENTD__SLACK_URL:
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      memory: 500Mi
