NOOSINV_DOCKER_REPO=
NOOSINV_DOCKER_USER=
NOOSINV_DOCKER_TOKEN=
NOOSINV_DOCKER_NAME=fluentd
NOOSINV_DOCKER_CONTEXT=./docker/exporter

NOOSINV_HELM_REPO="op://Tech-shared/AWS ECR - root/URL"
NOOSINV_HELM_NAME=noos-prod/kube-logs
