apiVersion: v1
kind: Service
metadata:
  name: exporter
  namespace: {{ .Release.Namespace }}
spec:
  # Reaching a daemonset
  # https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#communicating-with-daemon-pods
  type: ClusterIP
  selector:
    app: fluent-bit-lb
  ports:
    - name: forward
      port: 24224
      targetPort: forward
    - name: http
      port: 9880
      targetPort: http

