# Fluent Bit parsers configuration
# https://docs.fluentbit.io/manual/pipeline/parsers

parsers:
  - name: json
    format: json
    time_key: time
    time_format: "%Y-%m-%dT%H:%M:%S.%L"
    time_keep: on
    # decode_field_as:
    #   - escaped_utf8: log
    #     action: do_next
    #   - json: log

  - name: docker
    format: json
    time_key: time
    time_format: "%Y-%m-%dT%H:%M:%S.%L"
    time_keep: on

  - name: cri
    format: regex
    regex: "^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$"
    time_key: time
    time_format: "%Y-%m-%dT%H:%M:%S.%L%z"
    time_keep: on
