# Fluent Bit parsers configuration
# https://docs.fluentbit.io/manual/pipeline/parsers

parsers:
  - name: json
    format: json
    time_key: time
    time_format: "%Y-%m-%dT%H:%M:%S.%L"
    time_keep: on
    decode_field_as: json log
