# Logging configuration for service events
pipeline:
  inputs:
    - name: forward
      listen: 0.0.0.0
      port: 24224
      tag: services.*

  filters:
    # Add tag field to record
    - name: record_modifier
      match: services.*
      record:
        tag: ${TAG}

  outputs:
    # Push all service logs to Slack (commented out)
    # - name: slack
    #   match: services.*
    #   webhook: ${FLUENTD__SLACK_URL}
