# Logging configuration for service events

pipeline:
  inputs:
    - name: forward
      tag_prefix: services.
      listen: 0.0.0.0
      port: 24224

  filters:
    # Add tag field to the log record
    # e.g.: input has tag 'my.app' then
    # append to record {"tag": "my.app"}
    - name: lua
      match: "services.*"
      script: /fluent-bit/etc/add_tag.lua
      call: add_tag_field

    # Dynamically restructure log format
    # move all keys except timestamp under 'log_object'
    - name: lua
      match: "services.*"
      script: /fluent-bit/etc/restructure_log.lua
      call: restructure_log

  outputs:
    # Push all service logs to Slack
    - name: slack
      match: "services.*"
      webhook: ${FLUENTBIT__SLACK_URL}
