# Logging configuration for service events
pipeline:
  inputs:
    - name: forward
      listen: 0.0.0.0
      port: 24224
      tag_prefix: services.

  filters:
    # Add tag field to the log record
    # e.g.: input has tag "my.app" then
    # append to record {"tag": "my.app"}
    - name: lua
      match: services.*
      script: add_tag.lua
      call: add_tag_field

    # Format records for Slack blocks
    - name: lua
      match: services.*
      script: format_slack_blocks.lua
      call: format_slack_blocks


  outputs:
    - name: stdout
      match: 'services.*'

    # Push all service logs to Slack
    - name: slack
      match: services.*
      webhook: ${FLUENTD__SLACK_URL}
