# Logging configuration for testing purposes

pipeline:
  inputs:
    - name: http
      tag: tests.*
      listen: 0.0.0.0
      port: 9880

  outputs:
    # Push all test logs to stdout
    - name: stdout
      match: 'tests.*'
      format: json_lines
